name: CI

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [Ubuntu-18, Ubuntu-20, Ubuntu-22, Debian-9, Debian-10, Debian-11, Debian-Testing, Debian-Experimental, Fedora-34]
        build_type: [Dev]
        cpp_compiler: [g++]
        cpp_version: [c++11]
        include:
          - name: Ubuntu-18
            # Uses gcc 7.5.0, clang 6.0.0, cmake 3.10.2
            image: "ubuntu:18.04"
            ubuntu: 18
            installer: apt
          - name: Ubuntu-20
            # Uses gcc 9.3.0, clang 10.0.0, cmake 3.16.3
            image: "ubuntu:20.04"
            ubuntu: 20
            installer: apt
          - name: Ubuntu-22
            # Uses gcc 12.2.0, clang 15.0.2, cmake 3.24.2
            image: "ubuntu:22.04"
            ubuntu: 22
            installer: apt
            CXXFLAGS: -Wno-stringop-overread
          - name: Debian-9
            # Uses gcc 6.3.0, clang 3.8.1, cmake 3.7.2
            image: "debian:stretch"
            installer: apt
          - name: Debian-10
            # Uses gcc 8.3.0, clang 7.0.1, cmake 3.13.4
            image: "debian:buster"
            installer: apt
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            cpp_version: c++17
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            cpp_version: c++20
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            c_compiler: clang
            cpp_compiler: clang++
            cpp_version: c++17
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            c_compiler: clang
            cpp_compiler: clang++
            cpp_version: c++20
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            build_type: RelWithDebInfo
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            c_compiler: clang
            cpp_compiler: clang++
          - name: Debian-11
            # Uses gcc 10.2.1, clang 11.0.1, cmake 3.18.4
            image: "debian:bullseye"
            installer: apt
            c_compiler: clang
            cpp_compiler: clang++
            CXXFLAGS: -fsanitize=address,undefined,integer -fno-sanitize-recover=all -fno-omit-frame-pointer
            LDFLAGS: -fsanitize=address,undefined,integer
          - name: Debian-Testing
            # Uses gcc 10.3.0, clang 11.1.0, cmake 3.21.3
            image: "debian:testing"
            installer: apt
            CXXFLAGS: -Wno-stringop-overread
          - name: Debian-Testing
            # Uses gcc 10.3.0, clang 11.1.0, cmake 3.21.3
            image: "debian:testing"
            installer: apt
            c_compiler: clang
            cpp_compiler: clang++
          - name: Debian-Experimental
            # Uses gcc 11, clang 14, cmake 3.21.3
            image: "debian:experimental"
            installer: apt
            CXXFLAGS: -Wno-stringop-overread
          - name: Debian-Experimental
            # Uses gcc 11, clang 14, cmake 3.21.3
            image: "debian:experimental"
            installer: apt
            c_compiler: clang-14
            cpp_compiler: clang++-14
          - name: Fedora-34
            # Uses gcc 11.2.1, clang 12.0.1, cmake 3.20.5
            image: "fedora:34"
            installer: dnf
            CXXFLAGS: -Wno-stringop-overread
          - name: Fedora-35
            # Uses gcc 11.2.1, clang 12.0.1, cmake 3.20.5
            image: "fedora:35"
            installer: dnf
            CXXFLAGS: -Wno-stringop-overread
    container:
      image: ${{ matrix.image }}
      env:
        LANG: en_US.UTF-8
        BUILD_TYPE: ${{ matrix.build_type }}
        CXXFLAGS: ${{ matrix.CXXFLAGS }}
        LDFLAGS: ${{ matrix.LDFLAGS }}
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cpp_compiler }}
        CPP_VERSION: ${{ matrix.cpp_version }}
        WITH_PROJ: ON
        APT_LISTCHANGES_FRONTEND: none
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Prepare container (apt)
        run: |
          apt-get update -qq
          apt-get install -y clang \
            cmake \
            g++ \
            git \
            libbz2-dev \
            libexpat1-dev \
            libgdal-dev \
            libgeos-dev \
            liblz4-dev \
            make \
            spatialite-bin \
            zlib1g-dev
        shell: bash
        if: matrix.installer == 'apt'
      - name: Install compiler
        shell: bash
        run: apt-get install -y clang-14
        if: matrix.cpp_compiler == 'clang++-14'
      - name: Prepare container (dnf)
        run: |
          dnf install --quiet --assumeyes \
              bzip2-devel \
              cmake \
              expat-devel \
              gcc-c++ \
              gdal-devel \
              geos-devel \
              git \
              lz4-devel \
              make \
              proj-devel \
              spatialite-tools \
              zlib-devel
        shell: bash
        if: matrix.installer == 'dnf'
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-from-git
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  ubuntu-latest:
    runs-on: ubuntu-20.04
    env:
      CC: clang-13
      CXX: clang++-13
      BUILD_TYPE: Dev
    steps:
      - name: Install new clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
          sudo apt-get update -q
          sudo apt-get install -yq clang-13
        shell: bash
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-ubuntu
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  macos11-dev:
    runs-on: macos-11.0
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-macos
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  macos11-release:
    runs-on: macos-11.0
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-macos
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  macos12-dev:
    runs-on: macos-12.0
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Dev
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-macos
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

  macos12-release:
    runs-on: macos-12.0
    env:
      CC: clang
      CXX: clang++
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-macos
      - uses: ./.github/actions/cmake
      - uses: ./.github/actions/build
      - uses: ./.github/actions/ctest

